### ISSUE TITLE
empty iphi.json

### ISSUE THREAD

**Issue by AudricWannaz** [sommerschield/iphi#1]
Hi,

First, thanks for the awesome work you are doing!
I have issues replicating the dataset generation step, what am I doing wrong?

Here are my working steps: 
1. I downloaded the repository and moved it in a local folder
2. I created a conda environment and installed the dependencies as required
3. I ran the code line python -m ithaca.data.iphi_download  --connections=1 (also with 50 or 100)
The line in 3. seems to work, but the result is, as far as I can tell, an empty iphi.json file. I attached a screenshot of the terminal, looks like it worked, but nothing was written/saved. What am I missing?

Best,

Audric Wannaz 

<img width="673" alt="Screenshot 2022-03-14 at 14 20 09" src="https://user-images.githubusercontent.com/34545101/158180147-78d8149b-8f97-43b8-8450-c938355c22f0.png">

**Comment by iassael** [comment]
Hi Audric, everything runs as expected, so I guess there is some dependency / nltk problem in your installation hidden by the try/catch statement.
